<?php
session_start();

if (!isset($_SESSION['loggedin'])) {
    header('Location: login.php');
    exit;
}

include "config.php";

date_default_timezone_set('America/Chicago');
$report_date = (date('H') >= 23) ? date('Y-m-d', strtotime('tomorrow')) : date('Y-m-d');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title><?php echo $report_date; ?> Daily Report</title>
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <style>
        .table-responsive {
            display: block;
            width: 100%;
            overflow-x: auto;
            -webkit-overflow-scrolling: touch;
        }
    </style>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#">DFWAM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/index.php">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Orders
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/index.php">Current Work Orders</a>
                        <a class="dropdown-item" href="/add.php">Add Work Order</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/nfns.php">Notes for Techs</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/print.php">Print Daily Report <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="logout.php">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid mt-4">
        <div class="row">
            <div class="col">
                <h2 class="text-center">Daily Report for <?php echo $report_date; ?></h2>
                <p class="text-center">Generated by: <strong><?php echo htmlspecialchars($_SESSION['name'] ?? ''); ?></strong></p>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col">
                <h3>Work Orders</h3>
                <div class="table-responsive shadow-sm rounded">
                    <table class="table table-bordered table-striped table-hover mb-0">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Room</th>
                                <th>Work To Be Done</th>
                                <th>Submitted By</th>
                                <th>Time</th>
                                <th>Completed Time</th>
                                <th>Completed By</th>
                                <th>Completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $query = $conn->prepare("SELECT * FROM `orders` WHERE DATE(time) = :report_date ORDER BY `id` DESC");
                            $query->bindParam(':report_date', $report_date);
                            $query->execute();
                            $data = $query->fetchAll(PDO::FETCH_ASSOC);

                            foreach ($data as $row) {
                                $status = $row['completed'] ? "Yes" : "No";
                                echo '<tr>
                                        <td>' . htmlspecialchars($row['id'] ?? '') . '</td>
                                        <td>' . htmlspecialchars($row['room'] ?? '') . '</td>
                                        <td>' . htmlspecialchars($row['work_to_be_done'] ?? '') . '</td>
                                        <td>' . htmlspecialchars($row['submitted_by'] ?? '') . '</td>
                                        <td>' . htmlspecialchars($row['time'] ?? '') . '</td>
                                        <td>' . htmlspecialchars($row['time_completed'] ?? '') . '</td>
                                        <td>' . htmlspecialchars($row['completed_by'] ?? '') . '</td>
                                        <td>' . $status . '</td>
                                    </tr>';
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <hr class="my-4">

        <div class="row mt-3">
            <div class="col">
                <h3>Notes for Next Shift</h3>
                <div class="table-responsive shadow-sm rounded">
                    <table class="table table-bordered table-striped table-hover mb-0">
                        <thead class="thead-dark">
                            <tr>
                                <th>ID</th>
                                <th>Timestamp</th>
                                <th>Notes</th>
                                <th>Engineer</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $stmt = $conn->prepare('SELECT * FROM notes_for_next_shift WHERE DATE(timestamp) = :report_date ORDER BY id DESC');
                            $stmt->bindParam(':report_date', $report_date);
                            $stmt->execute();
                            $notes_data = $stmt->fetchAll(PDO::FETCH_ASSOC);

                            foreach ($notes_data as $row):
                            ?>
                            <tr>
                                <td><?php echo htmlspecialchars($row['id'] ?? ''); ?></td>
                                <td><?php echo htmlspecialchars($row['timestamp'] ?? ''); ?></td>
                                <td><?php echo htmlspecialchars($row['notesfornextshift'] ?? ''); ?></td>
                                <td><?php echo htmlspecialchars($row['engineer'] ?? ''); ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>